### ISSUE TITLE
Definir qual licença utilizar no projeto do UFABC Next

### ISSUE THREAD

**Issue by EgidioHPaixao** [FeoSilva/ufabc-next-web#13]
Mensagem do professor Paulo Meirelles: 

é importante colocar uma licença no repositório do projeto; posso ajudar nessa definição, caso tenham dúvidas.
No início do quadrimestre, disponibilizei uma palestra minha sobre software livre para quem precisar entender melhor: https://drive.google.com/file/d/1oxEf44llt1ccjbvzxCAuSje2S4-ytXvT/view
a partir de 1h01min começo a explicar sobre as licenças

**Comment by FeoSilva** [comment]
Sugestão do professor: AGPL @luiso33
