### ISSUE TITLE
Adicionar atalho para os grupos de whatsapp das disciplinas

### ISSUE THREAD

**Issue by EgidioHPaixao** [FeoSilva/ufabc-next-web#2]
A cada quadrimestre, é criado um "docs google" com as disciplinas/turmas e os respectivos grupos de whatsapp criados para os alunos.
Esse link é trocado entre os próprios alunos, sem um local centralizado.
A ideia é que o UFABC Next sirva como centro para o aluno obter o link e consultar o "docs google". no futuro, pode ser evoluído para que o próprio next gere este arquivo

**Comment by vini-reis** [comment]
Adicionado link criado na task #11, aguardando ajustes para realizar o teste local.
