### ISSUE TITLE
Ajustar planilha de disciplinas

### ISSUE THREAD

**Issue by EgidioHPaixao** [FeoSilva/ufabc-next-web#20]
* ajustar API do ufabc next para obter as disciplinas ofertadas
* incluir a data do quad que será ofertado (ex: 2021.3)
* além de informar o nome da disciplina, informar o nome do professor de cada turma
* fazer chamada automatica para o rebrandly, atualizando o redirecionamento

Importante: como funcionará para materias de turmas integradas? (ex: femec, feterm, etc)

**Comment by arthurlimadossantos** [comment]
- Ajustar API do ufabc next para obter as disciplinas ofertadas (OK)
- Incluir a data do quad que será ofertado (ex: 2021.3)
- Informar o nome da disciplina, informar o nome do professor de cada turma (OK)
- Chamada automática para o rebrandly, atualizando o redirecionamento

**Comment by arthurlimadossantos** [comment]
https://script.google.com/u/1/home/projects/1V1w6_2x6n29AXG-edZl-114XdWMbeCfUwNuX6Eedi_ok-r80d2wQvIlE/edit
