### ISSUE TITLE
Gerar planilha excel com as turmas/disciplinas do próximo quadrimestre

### ISSUE THREAD

**Issue by EgidioHPaixao** [FeoSilva/ufabc-next-web#3]
Num futuro, o ufabc next poderá gerar os próprios grupos de whatsapp para os alunos.
Contudo, antes de pensar na integração com API de whatsapp, uma forma seria gerar uma planilhas google com as turmas/disciplinas ofertadas para que os alunos criem os grupos de whatsapp e informem o link.
Assim, o objetivo dessa issue seria uma rotina para que a cada quad , uma planilha google fosse gerada para que os alunos informes o link dos grupos de whats ( vale discutir como esse link será inserido pelos usuarios, se via forms ou se via edição na propria planilha)

**Comment by arthurlimadossantos** [comment]
https://script.google.com/u/1/home/projects/1V1w6_2x6n29AXG-edZl-114XdWMbeCfUwNuX6Eedi_ok-r80d2wQvIlE/edit
